### ISSUE TITLE
Explain theme variables

### ISSUE THREAD

**Issue by thieung** [pagankeymaster/nvim-config#5]
Hi @dharmx ,
Thanks for your nice config, I'm currently reference your config in order to write my own config. I'm very interested in your  colorscheme system. 
Could  you please share what is the meaning of your pallets? Such as base16 (https://github.com/chriskempson/base16/blob/main/styling.md) or base46 (https://github.com/NvChad/base46#understanding-theme-variables)

**Comment by dharmx** [comment]
Really, really sorry for the late reply (although it looks like you have long solved the problem) but the theme variables does not have any meaning. I have removed that module completely now.
